# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
# created-by: conda 25.11.1
_openmp_mutex=4.5=7_kmp_llvm
bzip2=1.0.8=hda65f42_8
ca-certificates=2026.1.4=hbd8a1cb_0
cpython=3.14.2=py314hd8ed1ab_100
filelock=3.20.3=pyhd8ed1ab_0
fmt=12.1.0=hff5e90c_0
fsspec=2026.1.0=pyhd8ed1ab_0
gmp=6.3.0=hac33072_2
gmpy2=2.2.1=py314h28848ee_2
icu=78.2=h33c6efd_0
jinja2=3.1.6=pyhcf101f3_1
ld_impl_linux-64=2.45=default_hbd61a6d_105
libabseil=20250512.1=cxx17_hba17884_0
libblas=3.11.0=5_h5875eb1_mkl
libcblas=3.11.0=5_hfef963f_mkl
libexpat=2.7.3=hecca717_0
libffi=3.5.2=h9ec8514_0
libgcc=15.2.0=he0feb66_16
libgcc-ng=15.2.0=h69a702a_16
libhwloc=2.12.2=default_hafda6a7_1000
libiconv=1.18=h3b78370_2
liblapack=3.11.0=5_h5e43f62_mkl
liblzma=5.8.1=hb9d3cd8_2
libmpdec=4.0.0=hb9d3cd8_0
libprotobuf=6.31.1=h49aed37_4
libsqlite=3.51.2=hf4e2dac_0
libstdcxx=15.2.0=h934c35e_16
libstdcxx-ng=15.2.0=hdf11a46_16
libtorch=2.9.1=cpu_mkl_hfee2a32_103
libuuid=2.41.3=h5347b49_0
libuv=1.51.0=hb03c661_1
libxml2=2.15.1=he237659_1
libxml2-16=2.15.1=hca6bf5a_1
libzlib=1.3.1=hb9d3cd8_2
llvm-openmp=21.1.8=h4922eb0_0
markupsafe=3.0.3=pyh7db6752_0
mkl=2025.3.0=h0e700b2_463
mpc=1.3.1=h24ddda3_1
mpfr=4.2.1=h90cbb55_3
mpmath=1.3.0=pyhd8ed1ab_1
ncurses=6.5=h2d0b736_3
networkx=3.6.1=pyhcf101f3_0
numpy=2.4.1=py314h2b28147_0
openssl=3.6.0=h26f9b46_0
optree=0.18.0=py314h9891dd4_0
pip=25.3=pyh145f28c_0
pybind11=3.0.1=pyh7a1b43c_0
pybind11-abi=11=hc364b38_1
pybind11-global=3.0.1=pyhc7ab6ef_0
python=3.14.2=h32b2ec7_100_cp314
python_abi=3.14=8_cp314
readline=8.3=h853b02a_0
setuptools=80.9.0=pyhff2d567_0
sleef=3.9.0=ha0421bc_0
sympy=1.14.0=pyh2585a3b_105
tbb=2022.3.0=hb700be7_2
tk=8.6.13=noxft_ha0e22de_103
typing-extensions=4.15.0=h396c80c_0
typing_extensions=4.15.0=pyhcf101f3_0
tzdata=2025c=hc9c84f9_1
zstd=1.5.7=hb78ec9c_6
